// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.app = {
    models: {}
  };

  app.models.Calendar = (function() {
    var cellSize, colorScale, format, getDay, getMonth, getMonthName, hashtags, height, pickColor, width;

    hashtags = function(eventText) {
      return eventText.split(" ").filter(function(el) {
        return el[0] === "#";
      });
    };

    width = 1240;

    height = 520;

    cellSize = 38;

    colorScale = ["rgb(200,200,200)", "rgb(165,0,38)", "rgb(215,48,39)", "rgb(244,109,67)", "rgb(253,174,97)", "rgb(254,224,139)", "rgb(255,255,191)", "rgb(217,239,139)", "rgb(166,217,106)", "rgb(102,189,99)", "rgb(26,152,80)", "rgb(0,104,55)"];

    getDay = d3.time.format("%d");

    getMonth = d3.time.format("%m");

    getMonthName = d3.time.format("%b");

    format = d3.time.format("%Y-%m-%d");

    pickColor = function(index) {
      return colorScale[index % colorScale.length];
    };

    function Calendar(data) {
      this.data = data;
      this.outputControllers = __bind(this.outputControllers, this);

      this.filterEvent = __bind(this.filterEvent, this);

      this.chooseColor = __bind(this.chooseColor, this);

      this.update = __bind(this.update, this);

      this.redraw = __bind(this.redraw, this);

      this.padCalendarData = __bind(this.padCalendarData, this);

      this.prepareHTML();
      this.drawMonthLabels();
      this.drawDayLabels();
      this.padCalendarData();
      this.redraw();
    }

    Calendar.prototype.prepareHTML = function() {
      return this.svg = d3.select("body").selectAll("svg").data(d3.range(2012, 2013)).enter().append("svg").attr("width", width).attr("height", height).append("g");
    };

    Calendar.prototype.drawMonthLabels = function() {
      return this.svg.selectAll(".text").data(function(year) {
        return d3.time.months(new Date(year, 0, 1), new Date(year + 1, 0, 1));
      }).enter().append("text").attr("x", function(date) {
        return -23 + cellSize;
      }).attr("y", function(date) {
        return 22 + getMonth(date) * cellSize;
      }).attr("class", "month-name").datum(getMonthName).text(function(monthName) {
        return monthName;
      });
    };

    Calendar.prototype.drawDayLabels = function() {
      return this.svg.selectAll(".text").data(function(year) {
        return d3.time.days(new Date(year, 0, 1), new Date(year + 1, 0, 1));
      }).enter().append("text").attr("x", function(date) {
        return 10 + getDay(date) * cellSize;
      }).attr("y", function(date) {
        return 35 + getMonth(date) * cellSize;
      }).attr("class", "month-name").datum(getDay).text(function(day) {
        return day;
      });
    };

    Calendar.prototype.padCalendarData = function() {
      var _this = this;
      return d3.time.days(new Date(2012, 0, 1), new Date(2013, 0, 1)).map(function(date) {
        if (!_this.data[format(date)]) {
          return _this.data[format(date)] = null;
        }
      });
    };

    Calendar.prototype.redraw = function() {
      var _this = this;
      return this.svg.selectAll(".day").data(function(d) {
        return d3.keys(_this.data);
      }).enter().append("rect").attr("height", cellSize).attr("class", "day").attr("fill", this.chooseColor).attr("x", function(d) {
        return parseInt(d.split("-")[2]) * cellSize;
      }).attr("y", function(d) {
        return parseInt(d.split("-")[1]) * cellSize;
      }).attr("width", cellSize).transition().duration(500).attr("fill-opacity", 1);
    };

    Calendar.prototype.update = function(filter) {
      this.filter = filter;
      return this.svg.selectAll(".day").transition().duration(500).attr("fill", this.chooseColor);
    };

    Calendar.prototype.chooseColor = function(d) {
      var colorIndex, data;
      if (this.data[d]) {
        data = this.filter ? this.data[d].filter(this.filterEvent) : this.data[d];
        colorIndex = data.length;
      } else {
        colorIndex = 0;
      }
      return pickColor(colorIndex);
    };

    Calendar.prototype.filterEvent = function(event) {
      return event.text.indexOf(this.filter) !== -1;
    };

    Calendar.prototype.outputControllers = function() {};

    Calendar.prototype.hashtags = function(eventText) {
      return eventText.split(" ").filter(function(el) {
        return el[0] === "#";
      });
    };

    return Calendar;

  })();

  $(function() {
    var sampleData, sampleEventData;
    sampleEventData = {
      text: "Test",
      created_at: new Date()
    };
    sampleData = {
      "2012-01-01": [sampleEventData],
      "2012-01-02": [sampleEventData],
      "2012-01-03": [sampleEventData, sampleEventData],
      "2012-01-04": [sampleEventData],
      "2012-01-05": [sampleEventData, sampleEventData, sampleEventData],
      "2012-01-06": [sampleEventData, sampleEventData, sampleEventData, sampleEventData],
      "2012-03-03": [sampleEventData],
      "2012-04-03": [sampleEventData, sampleEventData, sampleEventData, sampleEventData, sampleEventData, sampleEventData],
      "2012-05-03": [sampleEventData]
    };
    return d3.select(self.frameElement).style("height", "910px");
  });

}).call(this);
