// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var buildEvent, hash;
    hash = {};
    buildEvent = function(text) {
      return {
        title: text,
        quantity: 1
      };
    };
    tweets.map(function(el) {
      var date, day, formattedDate, month;
      date = new Date(el.created_at);
      month = date.getMonth() + 1;
      day = date.getDate();
      formattedDate = date.getFullYear() + "-" + (month > 9 ? month : "0" + month) + "-" + (day > 9 ? day : "0" + day);
      if (hash[formattedDate]) {
        return hash[formattedDate].push(buildEvent(el.text));
      } else {
        return hash[formattedDate] = [buildEvent(el.text)];
      }
    });
    console.log(hash);
    return new app.models.Calendar(hash);
  });

}).call(this);
